apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ebpf-profiler-collector.yaml
  - jaeger-collector.yaml
  - opentelemetry-collector.yaml
  - opentelemetry-collector-rbac.yaml
configMapGenerator:
  - name: opentelemetry-demo-dashboards
    namespace: observability
    files:
      - dashboards/NGINX-metrics.json
      - dashboards/demo-dashboard.json
      - dashboards/exemplars-dashboard.json
      - dashboards/linux-dashboard.json
      - dashboards/postgresql-dashboard.json
      - dashboards/spanmetrics-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"