apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  mode: daemonset
  args:
    feature-gates: service.profilesSupport,receiver.postgresql.separateSchemaAttr
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_K8S_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: OTEL_K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: OTEL_K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: GOMEMLIMIT
      value: 320MiB
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.161.0
  resources:
    limits:
      memory: 400Mi
  serviceAccount: opentelemetry-collector      
  volumes:
    - name: hostfs
      hostPath:
        path: /
        type: Directory
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      mountPropagation: HostToContainer
      readOnly: true
  ports:
    - name: jaeger-compact
      port: 6831
      hostPort: 6831
      protocol: UDP
    - name: jaeger-grpc
      port: 14250
      hostPort: 14250
      protocol: TCP
    - name: jaeger-thrift
      port: 14268
      hostPort: 14268
      protocol: TCP
    - name: metrics
      port: 8888
      protocol: TCP
    - name: otlp
      port: 4317
      hostPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      hostPort: 4318
      protocol: TCP
    - name: zipkin
      port: 9411
      hostPort: 9411
      protocol: TCP
  config:
    connectors:
      span_metrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        aggregation_cardinality_limit: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    exporters:
      debug: {}
      otlp_grpc/firepit:
        endpoint: firepit.otel-demo.svc.cluster.local:4317
        tls:
          insecure: true
      otlp_grpc/jaeger:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        sending_queue:
          batch: {}
        tls:
          insecure: true
      otlp_http/loki:
        endpoint: http://loki-gateway.observability.svc.cluster.local/otlp
        encoding: json
        tls:
          insecure: true          
      otlp_http/prometheus:
        endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/otlp
        sending_queue:
          batch: {}
        tls:
          insecure: true
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      k8s_leader_elector/k8s_cluster:
        auth_type: serviceAccount
        lease_name: k8s.cluster.receiver.opentelemetry.io
        lease_namespace: observability
      k8s_observer:
        auth_type: serviceAccount
        node: ${env:K8S_NODE_NAME}
    processors:
      batch: {}
      filter/sanitize_profiles:
        error_mode: ignore
        profiles:
          profile:
            - IsMatch(resource.attributes["service.name"], "containerd-shim-.*")
      gen_ai_normalizer:
        sources:
          - name: openllmetry
      k8s_attributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.replicaset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.job.name
            - k8s.job.uid
            - k8s.container.name
            - k8s.cronjob.name
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - container.image.tag
            - container.image.name
            - k8s.cluster.uid
            - service.namespace
            - service.name
            - service.version
            - service.instance.id
          otel_annotations: true
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: container.id
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      redaction:
        allow_all_keys: true
        blocked_key_patterns:
          - demo\.payment\.card_pin
          - password
          - secret
        ignored_keys:
          - demo.payment.card_number
        summary: info
      resource:
        attributes:
          - action: insert
            from_attribute: k8s.pod.uid
            key: service.instance.id
      resource_detection:
        detectors:
          - env
          - system
      transform/redact_sensitive_data:
        error_mode: ignore
        trace_statements:
          - context: span
            statements:
              - delete_key(attributes, "demo.payment.card_cvv") where attributes["demo.payment.card_cvv"] != nil
              - set(attributes["user.hash"], SHA256(attributes["user.email"])) where attributes["user.email"] != nil
              - delete_key(attributes, "user.email") where attributes["user.email"] != nil
              - replace_pattern(attributes["demo.payment.card_number"], "^\\d{4}-\\d{4}-\\d{4}-", "****-****-****-") where attributes["demo.payment.card_number"] != nil
      transform/sanitize_logs:
        error_mode: ignore
        log_statements:
          - context: scope
            statements:
              - set(attributes["otelcol_signal"], attributes["otelcol.signal"]) where attributes["otelcol.signal"] != nil and not IsMap(attributes["otelcol.signal"])
              - delete_key(attributes, "otelcol.signal") where attributes["otelcol_signal"] != nil
      transform/sanitize_spans:
        error_mode: ignore
        trace_statements:
          - context: span
            statements:
              - set_semconv_span_name("1.43.0", "original_span_name")
    receivers:
      host_metrics:
        collection_interval: 10s
        root_path: /hostfs
        scrapers:
          cpu: {}
          disk: {}
          filesystem:
            exclude_fs_types:
              fs_types:
                - autofs
                - binfmt_misc
                - bpf
                - cgroup2
                - configfs
                - debugfs
                - devpts
                - devtmpfs
                - fusectl
                - hugetlbfs
                - iso9660
                - mqueue
                - nsfs
                - overlay
                - proc
                - procfs
                - pstore
                - rpc_pipefs
                - securityfs
                - selinuxfs
                - squashfs
                - sysfs
                - tracefs
              match_type: strict
            exclude_mount_points:
              match_type: regexp
              mount_points:
                - ^/dev($|/)
                - ^/proc($|/)
                - ^/sys($|/)
                - ^/run/k3s/containerd($|/)
                - ^/var/lib/docker($|/)
                - ^/var/lib/kubelet($|/)
                - ^/snap($|/)
          load: {}
          memory: {}
          network: {}
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      k8s_cluster:
        collection_interval: 10s
        k8s_leader_elector: k8s_leader_elector/k8s_cluster
      kafka_metrics:
        brokers:
          - kafka.otel-demo.svc.cluster.local:9092
        collection_interval: 10s
        scrapers:
          - brokers
          - topics
          - consumers
      kubelet_stats:
        auth_type: serviceAccount
        collection_interval: 20s
        endpoint: ${env:K8S_NODE_IP}:10250
        insecure_skip_verify: true
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_headers:
                - content-type
                - traceparent
                - baggage
              allowed_origins:
                - http://*
                - https://*
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
      prometheus/ad:
        config:
          scrape_configs:
            - job_name: ad
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ad.otel-demo.svc.cluster.local:9465
      receiver_creator/metrics:
        discovery:
          enabled: true
        watch_observers:
          - k8s_observer
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
        - health_check
        - k8s_observer
        - k8s_leader_elector/k8s_cluster
      pipelines:
        logs:
          exporters: [debug, otlp_http/loki]
          processors: [k8s_attributes, memory_limiter, resource_detection, resource, transform/sanitize_logs]
          receivers: [otlp]
        metrics:
          exporters: [debug, otlp_http/prometheus]
          processors: [k8s_attributes, memory_limiter, resource_detection, resource]
          receivers: [otlp, kafka_metrics, span_metrics, prometheus/ad, receiver_creator/metrics, host_metrics, kubelet_stats, k8s_cluster]
        profiles:
          exporters: [debug, otlp_grpc/firepit]
          processors: [k8s_attributes, memory_limiter, resource_detection, resource, filter/sanitize_profiles]
          receivers: [otlp]
        traces:
          exporters: [otlp_grpc/jaeger, debug, span_metrics]
          processors: [k8s_attributes, memory_limiter, resource_detection, resource, transform/sanitize_spans, gen_ai_normalizer, transform/redact_sensitive_data, redaction]
          receivers: [otlp, jaeger, zipkin]