apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: opentelemetry-operator-demo
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.13.0
    chart: metrics-server
    helm:
      releaseName: metrics-server
      values: |
        args:
          - --kubelet-insecure-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - PruneLast=true
    retry:
      limit: -1
