apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: opentelemetry-operator-demo
  source:
    chart: pyroscope
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.3.1
    helm:
      releaseName: pyroscope
      values: |
        pyroscope:
          structuredConfig:
            limits:
              ingestion_relabeling_rules:
                - action: labelmap
                  regex: ^process.executable.name$
                  replacement: service_name
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
    retry:
      limit: -1